apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
- ns.yaml
patches:
- path: ./patches/longhorn-default-setting.yaml
  target:
    kind: ConfigMap
    name: longhorn-default-setting