apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchdb
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: couchdb
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - chart: couchdb
    repoURL: https://apache.github.io/couchdb-helm
    targetRevision: 4.5.6
    helm:
      valuesObject:
        couchdbConfig.couchdb.uuid: 2b83ffe8b135492ebc6ff149b57ae9b4
  - path: k8s/apps/manifests/couchdb
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true