apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 68.3.2
      helm:
        valuesObject:
          grafana:
            persistence:
              enabled: true
              type: sts
              storageClassName: longhorn
              accessModes:
                - ReadWriteOnce
              size: 1Gi
              finalizers:
                - kubernetes.io/pvc-protection
          prometheus:
            prometheusSpec:
              remoteWrite:
              - url: https://prometheus-prod-49-prod-ap-northeast-0.grafana.net/api/prom/push
                basicAuth:
                    username:
                      name: kube-prometheus-secret
                      key: prometheus-username
                    password:
                      name: kube-prometheus-secret
                      key: prometheus-password
              replicaExternalLabelName: "__replica__"
              externalLabels: {cluster: "furonverse"}
    - path: k8s/system/manifests/prometheus-stack
      repoURL: https://github.com/furon-kuina/furonverse
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
