apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: cloudflare-tunnel-token
  data:
    - secretKey: CLOUDFLARE_TUNNEL_TOKEN
      remoteRef:
        key: k8s
        property: cloudflare-tunnel-token
