apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: artifact-registry-sa-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .mysecret }}` }}"
    name: artifact-registry-sa-key
    creationPolicy: Owner
  data:
    - secretKey: mysecret
      remoteRef:
        key: artifact-registry-sa-key
