apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: artifact-registry-sa-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ `{{ .artifact-registry-sa-key }}` }}"
    name: artifact-registry-sa-key
  data:
    - secretKey: artifact-registry-sa-key
      remoteRef:
        key: k8s
        property: artifact-registry-sa-key
