apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ipes-controller
  name: ipes-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: ipes-controller
  template:
    metadata:
      labels:
        pod: ipes-controller
    spec:
      serviceAccountName: ipes-controller-sa
      imagePullSecrets:
        - name: artifact-registry-sa-key
      containers:
        - image: asia-northeast1-docker.pkg.dev/furonverse/furonverse/imagepullexternalsecrets-controller:v0.1.3
          name: ipes-controller
          env:
            - name: DESIRED_EXTERNAL_SECRET
              valueFrom:
                configMapKeyRef:
                  key: desired-ipes
                  name: ipes-cm
            - name: TRIGGER_SECRET_NAME
              value: artifact-registry-sa-key
