apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipes-controller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["external-secrets.io"]
  resources: ["externalsecrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ipes-controller
subjects:
- kind: ServiceAccount
  name: ipes-controller-sa
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: ipes-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ipes-controller-sa
  namespace: kube-system