apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common-gateway
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - path: k8s/system/manifests/common-gateway
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true