apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: projectcontour
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - repoURL: https://github.com/projectcontour/contour
    path: examples/render
    targetRevision: "1.30"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true