apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: projectcontour
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - chart: contour
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 19.5.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true