apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: envoy-gateway-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - repoURL: https://github.com/envoyproxy/gateway
    path: charts/gateway-helm
    targetRevision: v1.2.4
    helm:
      valuesObject:
        service:
          annotations: {}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true