apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: {{ .Values.metadata.namespace }}
spec:
  destination:
    namespace: external-secrets
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.10.7
  - path: k8s/system/manifests/external-secrets
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.global.charts_version }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true