apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: {{ .Values.metadata.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: longhorn-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: "1.5.1"
    helm:
      valuesObject:
        persistence:
          defaultClassReplicaCount: 2
  - path: k8s/system/manifests/longhorn
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.global.charts_version }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true