apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: {{ .Values.metadata.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: promtail
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources:
  - path: k8s/system/manifests/promtail
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.global.charts_version }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true