apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: postgres-secret
  data:
  - secretKey: POSTGRES_USER
    remoteRef:
      key: k8s
      property: ttrss-postgres-user
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: k8s
      property: ttrss-postgres-password
  - secretKey: POSTGRES_DB
    remoteRef:
      key: k8s
      property: ttrss-postgres-db
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: app-secret
  data:
  - secretKey: ADMIN_USER_PASS
    remoteRef:
      key: k8s
      property: ttrss-admin-password