apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tt-rss
resources:
- ./ns.yaml
- ./httproute.yaml
- ./external-secrets.yaml
- ./pvc.yaml
- ./tt-rss.yaml
- ./cm.yaml
- ./service.yaml