apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: postgres:15-alpine
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-storage
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: cthulhoo/ttrss-fpm-pgsql-static:59b94a9e
          volumeMounts:
            - mountPath: /var/www/html
              name: app-storage
          env:
            - name: TTRSS_DB_HOST
              value: "postgres"
            - name: TTRSS_DB_NAME
              value: ttrss
            - name: TTRSS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: TTRSS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
        - name: updater
          image: cthulhoo/ttrss-fpm-pgsql-static:59b94a9e
          volumeMounts:
            - mountPath: /var/www/html
              name: app-storage
          env:
            - name: TTRSS_DB_HOST
              value: "postgres"
            - name: TTRSS_DB_NAME
              value: ttrss
            - name: TTRSS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: TTRSS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          command: ["/opt/tt-rss/updater.sh"]
        - name: nginx
          image: cthulhoo/ttrss-web-nginx:latest
          volumeMounts:
            - mountPath: /var/www/html
              name: app-storage
              readOnly: true
          env:
          - name: RESOLVER
            value: kube-dns.kube-system.svc.cluster.local
          ports:
            - containerPort: 80
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-pvc
