apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsm
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            namespace: external-secrets
            name: gcpsm-secret # this secret contains the service account's access key, thus not managed by VCS
            key: secret-access-credentials
      projectID: furonverse
