apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm               # name of the SecretStore (or kind specified)
  target:
    name: test-secret  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: key-test  # name of the GCPSM secret key
    remoteRef:
      key: test