apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-endpoint
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: loki-endpoint
  data:
  - secretKey: loki-endpoint
    remoteRef:
      key: k8s
      property: loki-endpoint