# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: harbor
#   namespace: harbor
# spec:
#   parentRefs:
#     - name: eg
#       namespace: envoy-gateway-system
#   hostnames:
#     - harbor.furonverse.com
#   rules:
#     - backendRefs:
#         - kind: Service
#           name: nginx
#           port: 80