apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: minio-secret
  data:
    - secretKey: root-user
      remoteRef:
        key: k8s
        property: minio-root-user
    - secretKey: root-password
      remoteRef:
        key: k8s
        property: minio-root-password
