apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: synology-iscsi
provisioner: csi.san.synology.com
reclaimPolicy: Retain
allowVolumeExpansion: true
