apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchdb
  namespace: argocd
spec:
  destination:
    namespace: couchdb
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: couchdb
      repoURL: https://apache.github.io/couchdb-helm
      targetRevision: 4.5.6
      helm:
        valuesObject:
          # https://github.com/apache/couchdb-helm/issues/39
          couchdbConfig:
            couchdb:
              uuid: 2b83ffe8b135492ebc6ff149b57ae9b4
              max_document_size: 50000000
            chttpd:
              require_valid_user: true
              max_http_request_size: 4294967296
            chttpd_auth:
              require_valid_user: true
            httpd:
              WWW-Authenticate: Basic realm=\"administrator\"
              enable_cors: true
            cors:
              credentials: true
              origins: "*"
          persistentVolume:
            enabled: true
          createAdminSecret: false
    - path: k8s/services/manifests/couchdb
      repoURL: https://github.com/furon-kuina/furonverse
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
