apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./couchdb.yaml
- ./tt-rss.yaml
patches:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
      name: couchdb
    patch: |-
      - op: replace
        path: /spec/sources/1/targetRevision
        value: $ARGOCD_APP_SOURCE_TARGET_REVISION
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
      name: tt-rss
    patch: |-
      - op: replace
        path: /spec/sources/0/targetRevision
        value: $ARGOCD_APP_SOURCE_TARGET_REVISION