apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: k8s/services/manifests/minio
      repoURL: https://github.com/furon-kuina/furonverse
      targetRevision: HEAD
    - chart: minio
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 16.0.0
      helm:
        valuesObject:
          global:
            defaultStorageClass: nfs-client
          persistence:
            size: 256Gi
          auth:
            existingSecret: minio-secret
            rootUserSecretKey: minio-root-user
            rootPasswordSecretKey: minio-root-password
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
