apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
spec:
  destination:
    namespace: minio-operator
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: k8s/services/manifests/minio/operator
      repoURL: https://github.com/furon-kuina/furonverse
      targetRevision: HEAD
    - path: k8s/services/manifests/minio
      repoURL: https://github.com/furon-kuina/furonverse
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tt-rss
  namespace: argocd
spec:
  destination:
    namespace: tt-rss
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: k8s/services/manifests/minio/operator
      repoURL: https://github.com/furon-kuina/furonverse
      targetRevision: HEAD
    - path: k8s/services/manifests/minio
      repoURL: https://github.com/furon-kuina/furonverse
      targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
