apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-nextcloud
  namespace: nextcloud
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - nextcloud.furonverse.com
  rules:
    - backendRefs:
        - kind: Service
          name: nextcloud
          port: 8080
