apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  # Avoid Too Many Redirects error
  # ArgoCD tries to handle TLS termination by itself, thus redirects all
  # HTTP requests to HTTPS. 
  # We make cloudflared handle TLS termination.
  server.insecure: "true"