apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  # Fix to ArgoCD stucking in Progressing state
  # cf: https://sublimer.hatenablog.com/entry/2022/07/24/162750
  resource.customizations.health.Service: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.loadBalancer ~= nil then
        hs.status = "Healthy"
        hs.message = "LoadBalancer status is healthy"
        return hs
      end
    end

    hs.status = "Progressing"
    hs.message = "Waiting for LoadBalancer"
    return hs
  resource.customizations.health.gateway.networking.k8s.io_GatewayClass: |
    hs = {}
    if obj.status and obj.status.conditions and obj.status.conditions[1] then
      local condition = obj.status.conditions[1]
      if condition.reason == "Accepted" and condition.status == "True" then
        hs.status = "Healthy"
        hs.message = "GatewayClass status is healthy"
        return hs
      end
    end

    hs.status = "Progressing"
    hs.message = "Waiting for GatewayClass"
    return hs