apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |-
    g, furonverse:furon, role:admin
    g, tenma.edamura@gmail.com, role:admin
  scopes: '[groups, email]'
