name: Format YAML using google/yamlfmt
# Trigger on push events to all branches except 'main'.
on:
  push:
    branches-ignore:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate GitHub Apps token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.4"
      - name: terarform fmt
        run: terraform fmt -recursive
      - name: Commit and push changes if any
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          # Check if any files have changed
          if [ -n "$(git status --porcelain)" ]; then
            echo "Formatting changes detected. Committing and pushing..."
            git add -A
            git commit -m "Auto Format"
            git push
          else
            echo "No formatting changes detected."
          fi