apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: github-client-id
      remoteRef:
        key: k8s
        property: argocd-github-client-id
    - secretKey: github-client-secret
      remoteRef:
        key: k8s
        property: argocd-github-client-secret
