apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
  - secretKey: dex.github.clientSecret
    remoteRef:
      key: argocd-github-sso-secret