apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute
  namespace: argocd
spec:
  hostnames:
  - argocd.furonverse.com
  parentRefs:
  - name: common
    namespace: kube-system
  rules:
  - backendRefs:
    - name: argocd-server
      port: 80