apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- github.com/argoproj/argo-cd//manifests/ha/cluster-install?ref=v2.13.3
- ./ns.yaml
- ./appproject.yaml
- ./httproute.yaml
patches: # adjusted to the cluster's worker node count
- target:
    kind: StatefulSet
    name: argocd-redis-ha-server
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
- target:
    kind: Deployment
    name: argocd-redis-ha-haproxy
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
- path: ./patches/argocd-cm.yaml
  target:
    kind: ConfigMap
    name: argocd-cm
- path: ./patches/argocd-cmd-params-cm.yaml
  target:
    kind: ConfigMap
    name: argocd-cmd-params-cm