apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: kube-prometheus-secret
  data:
    - secretKey: prometheus-username
      remoteRef:
        key: k8s
        property: prometheus-username
    - secretKey: prometheus-password
      remoteRef:
        key: k8s
        property: prometheus-password
        
